# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNoUGQJ2l_PMtvr-nhejji-VDNS4PDW7
"""

import sqlite3
import pandas as pd

# Connect to the SQLite database file
conn = sqlite3.connect('pharmeasy.db')

# Load the tables into Pandas DataFrames
orders_df = pd.read_sql_query("SELECT * FROM orders_clean", conn)
regions_df = pd.read_sql_query("SELECT * FROM regions_master", conn)

# Display data overview and schema
print("Orders Clean Sample:")
print(orders_df.head())
print("\nRegions Master Sample:")
print(regions_df.head())

# Merge order dataset with regions master to get state and tier metadata
df = pd.merge(orders_df, regions_df, on='region', how='left')
df["order_date"] = pd.to_datetime(df["order_date"])
df["month"] = df["order_date"].dt.strftime("%B %Y")

import streamlit as st
import plotly.express as px

# Streamlit Page Setup
st.set_page_config(
    page_title="Pharma Sales Analytics",
    page_icon="💊",
    layout="wide"
)

# ---------------------------------------------------------
# Synthetic Dataset Creation (Self-Contained)
# ---------------------------------------------------------
@st.cache_data
def load_data():
    return df

# ---------------------------------------------------------
# Sidebar: Interactive Region Filter
# ---------------------------------------------------------
st.sidebar.title("Filters")
region_options = ["All"] + list(df['region'].unique())
selected_region = st.sidebar.selectbox("Select Region", region_options)

# Filter Dataframe
if selected_region != "All":
    filtered_df = df[df['region'] == selected_region]
else:
    filtered_df = df.copy()

st.title("💊 Pharmaceutical Sales & Revenue Dashboard")
st.markdown("Guntur sales surging +122.19% from April to May 2026")
st.info(
        "Total sales reached ₹3,265,191 across 2,100 unique orders, generating a total profit of ₹492,279."
        "Across the quarter, regional sales trajectories remained steady, highlighted by Guntur sales surging +122.19% from April to May 2026."
        "Hyderabad led regional volume while Medical Devices dominated product categories with a 31% share, followed by Lab Tests (11.9%), Personal Care (8.34%), OTC Medicines (6.65%), and Unknown (2.2%)."
        "To capture high-margin demand, inventory and supply chain resources focus on top-performing categories like Medical Devices."
        "Scroll down to explore detailed category shares, regional trends, and itemized transaction tables across Level 2 and Level 3 analytics."
        )

# ---------------------------------------------------------
# LEVEL 1: OVERVIEW KPI CARDS
# ---------------------------------------------------------
st.subheader("Level 1: Executive KPI Overview")
total_sales = filtered_df["sales_inr"].sum()
total_profit = filtered_df["profit_inr"].sum()

# Distinct count of order_id per acceptance criteria
distinct_order_count = filtered_df["order_id"].nunique()

col1, col2, col3 = st.columns(3)
col1.metric("Total Sales (INR)", f"₹{total_sales:,.0f}")
col2.metric("Total Profit (INR)", f"₹{total_profit:,.0f}")
col3.metric("Unique Orders Count", f"{distinct_order_count}")

st.divider()

# ---------------------------------------------------------
# LEVEL 2: CHARTS & CATEGORY BREAKDOWN
# ---------------------------------------------------------
st.subheader("Level 2: Category & Regional Analytics")

c1, c2 = st.columns(2)

with c1:
    # Chart 1: Line / Trend Chart across continuous temporal axis (Months)
    trend_data = filtered_df.groupby(['month', 'region'])['sales_inr'].sum().reset_index()
    month_order = ["April 2026", "May 2026", "June 2026"]
    trend_data['month'] = pd.Categorical(trend_data['month'], categories=month_order, ordered=True)
    trend_data = trend_data.sort_values('month')

    fig_line = px.line(
        trend_data,
        x="month",
        y="sales_inr",
        color="region",
        markers=True,
        title="What is the monthly sales trajectory by region?",
        labels={"sales_inr": "Sales Amount (INR ₹)", "month": "Month (Continuous Scale)"}
    )
    # Anti-pattern compliance: Y-axis starts strictly at ZERO
    fig_line.update_yaxes(rangemode="tozero")
    st.plotly_chart(fig_line, use_container_width=True)

with c2:
    # Chart 2: Part-of-Whole / Donut Chart (Max 6 categories)
    cat_data = filtered_df.groupby('category')['sales_inr'].sum().reset_index()
    fig_pie = px.pie(
        cat_data,
        names="category",
        values="sales_inr",
        hole=0.4,
        title="How do medicine categories share overall sales volume?",
        labels={"sales_inr": "Sales Amount (INR ₹)", "category": "Medicine Category"}
    )
    fig_pie.update_traces(textinfo="percent+label")
    st.plotly_chart(fig_pie, use_container_width=True)

# Chart 3: Comparison Bar Chart
bar_data = filtered_df.groupby('region')['sales_inr'].sum().reset_index()
fig_bar = px.bar(
    bar_data,
    x="region",
    y="sales_inr",
    title="Which regions contribute most to total sales volume?",
    labels={"sales_inr": "Total Sales Amount (INR ₹)", "region": "Geographic Region"},
    color_discrete_sequence=['#0284c7'] # Single color per series rule
)
# Anti-pattern compliance: Y-axis starts strictly at ZERO
fig_bar.update_yaxes(rangemode="tozero")
st.plotly_chart(fig_bar, use_container_width=True)

st.divider()

# ---------------------------------------------------------
# LEVEL 3: DETAIL LEVEL DATA TABLE
# ---------------------------------------------------------
st.subheader("Level 3: Region & Monthly Detailed Data Table")

detail_table = filtered_df.groupby(['region', 'month', 'category']).agg(
    order_count=('order_id', 'nunique'),
    sales=('sales_inr', 'sum'),
    profit=('profit_inr', 'sum')
).reset_index()

st.dataframe(
    detail_table.style.format({
        "sales": "₹{:,.0f}",
        "profit": "₹{:,.0f}"
    }),
    use_container_width=True
)